In [1]:
import numpy as np

# Breve introducción a numpy

El objeto base de los numpy son los arrays N dimensionales. `ndarray`

Se pueden crear arrays a partir de listas de python:

In [2]:
#lista de python:
plist=[1,2,3,4,5]
plist

[1, 2, 3, 4, 5]

In [3]:
#array de numpy:
a1D=np.array(plist)
a1D

array([1, 2, 3, 4, 5])

A diferencia de las listas de python los arrays de numpy soportan operaciones aritméticas.

## Aritmetica contra escalares

se aplican a cada coordenada contra el escalar

In [4]:
#Producto por un escalar
a1D*2

array([ 2,  4,  6,  8, 10])

In [5]:
#Suma contra un escalar
a1D+1

array([2, 3, 4, 5, 6])

In [6]:
#Potenciación
a1D**2

array([ 1,  4,  9, 16, 25])

## Aritmética array a array

In [7]:
b1D=np.array([5,4,3,2,1])
b1D

array([5, 4, 3, 2, 1])

In [8]:
#suma
a1D+b1D

array([6, 6, 6, 6, 6])

In [9]:
#producto
a1D*b1D

array([5, 8, 9, 8, 5])

In [10]:
#potenciación
a1D**b1D

array([ 1, 16, 27, 16,  5])

## Operaciones Vectoriales

In [11]:
#Producto Vectorial. Se hace mediante el operador arroba
a1D @ b1D

35

In [12]:
#Vemos que coincide con la suma del producto coordenada a coordenada
(a1D*b1D).sum()

35

In [13]:
#Ademas del operador @ llama a la función dot()
np.dot(a1D,b1D)

35

## Funciones en numpy, parte 1

en la sección de arriba vimos dot() y sum(). La mayoría de las funciones que reciben un array como argumento pueden llamarse como función o como método del objeto array

In [14]:
np.sum(a1D)

15

In [15]:
a1D.sum()

15

Otras funciones típicas

In [16]:
#media
a1D.mean()

3.0

In [17]:
#varianza
a1D.var()

2.0

In [18]:
#exponenciación
np.exp(1)

2.718281828459045

## Dimensiones

Los arrays pueden tener K dimensiones.  Comencemos con el caso mas sencillo de 2 dimensiones, pero las operaciones pueden generalizar independientemente del número de dimensiones:

In [19]:
#Los arrays pueden formarse a partir de listas de listas
a2D=np.array([[1,2,3],[4,5,6]])
a2D

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#A partir de 2 dimensiones podemos transponer los arrays. De nuevo hay 3 sabores para esto:

np.transpose(a2D)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
a2D.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
a2D.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
#El producto punto esta definido también para múltiples dimensiones, y resulta en el producto matricial:

a2D.T @ a2D

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [24]:
a2D @ a2D.T

array([[14, 32],
       [32, 77]])

Podemos obtener infomación de las dimensiones de un array

In [25]:
#Numero de dimensiones
a2D.ndim

2

In [26]:
#Cardinalidad en cada dimensión
a2D.shape

(2, 3)

In [27]:
#Candtidad de elementos totales
a2D.size

6

In [28]:
#Size coincide con la productoria de las cardinalidades.
np.prod(a2D.shape)

6

## Generación de arrays

In [29]:
#el operador range en python produce un generator, que es lento.
#En numpy es mejor usar arange, que tiene la misma interface que range()
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
#Tambien funciona definiendo rangos
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [31]:
#Muy utiles son tambien la generación de zeros y unos.


np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
#Ambas funciones reciben una tupla de cardinalidades (o shape) como argumento
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
#La funcion eye generar una matriz identidad:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
#la funcion diag, genera una matriz diagonal a partir de un array
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Cambio de dimensionalidad

In [36]:
a100=np.arange(100)
a100

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
#La función reshape permite cambiar la dimension
aC=np.reshape(a100,(10,10))
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
#Reshape acepa que una cardinalidad sea -1, autocompletanndo esa dimension para que "cierre"
np.reshape(a100,(10,-1,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

## Indexación:

In [39]:
as10=np.arange(0,100,10)
as10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
#numpy acepta python slices
#la syntaxis es comienzo : fin
as10[1:5]

array([10, 20, 30, 40])

In [41]:
#notar que el valor del final es exclusivo, es decir as10[5] no esta incluido en el silice anterior
as10[5]

50

In [42]:
#si un valor del slice no se elije se utiliza los valores por defecto
#0 para el comienzo
as10[:5]

array([ 0, 10, 20, 30, 40])

In [43]:
#la cardinalidad para el fin
as10[3:]


array([30, 40, 50, 60, 70, 80, 90])

In [44]:
#tambien se aceptan valores negativos para indicar para indicar la cardinalidad - n
#por ejemplo para quitar el ultimo valor
as10[:-1]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [45]:
#La sintaxis de slices acepta un 3er parametro llamado stride, que es el paso,
# por ejemplo para quedarnos con los elementos pares
as10[::2]

array([ 0, 20, 40, 60, 80])

In [46]:
#y para los impares, arrancamos con el primero
as10[1::2]

array([10, 30, 50, 70, 90])

In [47]:
# el stride puede ser negativo, lo que invierte el array
as10[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [48]:
#numpy acepta indexacion multidimensional, por ejemplo para
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
#Podemos definir ambas coordenadas en el mismo corchete
aC[0,1]

1

In [50]:
aC[1,0]

10

In [51]:
#La indexación multidmensional tambien acepta slices, por ejemplo:
#Para cortar en la 5ta fila y la 3ra columna
aC[:5,:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [52]:
#Si queremos dejar una dimensión completa, se dejan los ":" vacios 
#para indicar que vamos desde 0 hasta la cardinalidad.

#Por ejemplo para quedarnos con la 3ra columna

aC[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [53]:
#Para la 3ra y 4ta
aC[:,3:5]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

## Asignación:

los operadores de signacion =, +=, etc, pueden ser aplicados contra las selecciones

In [54]:
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
#Incrementa las 3 primeras
aC[:3]+1
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:
#Asigna 0 a la ultimas 3 columnas
aC[:,-3:]=0
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  0,  0,  0],
       [10, 11, 12, 13, 14, 15, 16,  0,  0,  0],
       [20, 21, 22, 23, 24, 25, 26,  0,  0,  0],
       [30, 31, 32, 33, 34, 35, 36,  0,  0,  0],
       [40, 41, 42, 43, 44, 45, 46,  0,  0,  0],
       [50, 51, 52, 53, 54, 55, 56,  0,  0,  0],
       [60, 61, 62, 63, 64, 65, 66,  0,  0,  0],
       [70, 71, 72, 73, 74, 75, 76,  0,  0,  0],
       [80, 81, 82, 83, 84, 85, 86,  0,  0,  0],
       [90, 91, 92, 93, 94, 95, 96,  0,  0,  0]])

In [57]:
#Multiplica por 2 las ultimas 2 filas
aC[-2:]*=2
aC

array([[  0,   1,   2,   3,   4,   5,   6,   0,   0,   0],
       [ 10,  11,  12,  13,  14,  15,  16,   0,   0,   0],
       [ 20,  21,  22,  23,  24,  25,  26,   0,   0,   0],
       [ 30,  31,  32,  33,  34,  35,  36,   0,   0,   0],
       [ 40,  41,  42,  43,  44,  45,  46,   0,   0,   0],
       [ 50,  51,  52,  53,  54,  55,  56,   0,   0,   0],
       [ 60,  61,  62,  63,  64,  65,  66,   0,   0,   0],
       [ 70,  71,  72,  73,  74,  75,  76,   0,   0,   0],
       [160, 162, 164, 166, 168, 170, 172,   0,   0,   0],
       [180, 182, 184, 186, 188, 190, 192,   0,   0,   0]])

## Indexacion avanzada

Ademas de slices se puede indexar utilizando listas de booleanos o indices.

### Indexación por listas

Por ejemplo, para quedarnos con las filas 3,6,y 8

In [58]:
aC=np.arange(100).reshape((10,10))
aC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
aC[[3,6,8]]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

El orden tambien puede variar

In [60]:
aC[[8,3,6]]

array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

### Indexación booleana

Por otro lado, la indexación booleana es buena para el filtrado o para armar mascaras... Por ejemplo, generemos una matriz de numeros ordenados aleatoreamente:

In [61]:
rC=np.random.choice(100,100,replace=False).reshape(10,10)
rC

array([[78, 81, 13, 92, 53, 12,  3, 50, 52, 90],
       [60, 68, 97, 27, 55, 10, 46, 74, 45, 47],
       [34, 77, 61, 28, 94, 22,  1, 89, 29, 17],
       [85, 21, 39, 19, 31, 93, 63,  0, 11,  5],
       [88,  9, 25, 33, 37, 59, 87,  4, 99, 70],
       [42, 95, 49,  2, 15, 75, 72,  7, 57, 24],
       [26, 54, 51, 56, 44, 76, 84, 82, 36, 91],
       [73,  6, 43, 32, 48,  8, 66, 83, 58, 67],
       [65, 40, 98, 41, 35, 18, 71, 80, 86, 16],
       [69, 20, 30, 23, 38, 62, 96, 64, 14, 79]])

In [66]:
#Elegimos las filas que tengan valores mayores a 50 en la 3er columna

rC[:,3]

array([92, 27, 28, 19, 33,  2, 56, 32, 41, 23])

In [67]:
rC[:,3]>50

array([ True, False, False, False, False, False,  True, False, False,
       False])

In [68]:
rC[rC[:,3]>50]

array([[78, 81, 13, 92, 53, 12,  3, 50, 52, 90],
       [26, 54, 51, 56, 44, 76, 84, 82, 36, 91]])